.TH spam-summary 1
.SH NAME
spam-summary \- produce terse report of new SPAM mail since last run
.SH SYNOPSIS
.B spam-summary [option]* [mail-folder]*
.SH OPTIONS
.TP
\fB-c|--config\fR config-file
Provide a different config file to be used instead of the default location of
${HOME}/etc/spam-summary/spam-summary.conf
.TP
\fB\-d|--debug\fR
Provide debug output to help trace a problem or understand an unexpected
behavior. If the debug flag is given twice, it will turn on additional
debug output.
.TP
\fB\-h|--help\fR
Print out options of the program, also showing some defaults
.TP
\fB-i|--ignore\fR
Ignore the timestamp file for the mailbox, so that all of the messages
in the entire mailbox are processed and not just the ones that arrived
since the last run of the program.
.TP
\fB\-l|--list\fR
List the mailboxes available, as listed in the config file.
.TP
\fB\-w|--wide\fR 
Produce a wide listing of up to 132 characters instead of the default 80.
.TP
\fB\-V|--version\fR
Print the version number of the program.
.SH EXAMPLES
.TP 0
 # Show the program usage

% spam-summary --help
 usage: spam-summary [option]* [mail-folder]*
   [-c|--config file]  :default=/home/rj/etc/spam-summary/spam-summary.conf
   [-d|--debug]*       :debug mode (give twice for level=2)
   [-h|--help]         :usage
   [-i|--ignore]       :ignore timestamp file
   [-l|--list]         :list mail-folders available
   [-w|--wide]         :wide output
   [-V|--version]      :print version (0.2)
.TP 0
 # List the mailboxes as given in the config file

% spam-summary --list
 folders:
   Likely Spam      (/home/rj/Mutt-mail/spam/almost-certainly-spam)
   Probably Spam    (/home/rj/Mutt-mail/spam/probably-spam)
   Best TLD         (/home/rj/Mutt-mail/spam/best-top-level-domain)
   mailer-daemon    (/home/rj/Mutt-mail/mailer-daemon)
.TP 0
 # Report new messages arrived for mailbox "Probably Spam" since last run

 # You can see here spammers forging addresses from my domain moxad.com
 # but it's obvious from the subject that all of these are spam.
 # The ignored 'evil' addresses are because they had patterns matched
 # by the 'ignore-from-patterns' directive in the config file.
 # In this case, I had specified a pattern of '-rj=moxad.com@'
 # This mailbox has a total of 106 messages since the mailbox was
 # last removed, and we received 5 new messages since the last run
 # of which 1 was ignored because it had a rejected pattern.

% spam-summary 'Probably Spam'
 New (valid) messages arrived for: Probably Spam

 info@moxad.com  =?utf-8?B?UGF5ZXogdm90cmUgZGV0dGUgcG91ciDDqXZpdGVyIGxlcyBww6...
 yhzt@hhlkoj.ru  Louis Vuitton Bags Up To 87% Off! Shop Online Now!
 rj@moxad.com    Settle your debt in order to avoid additional fees.
 MAILER-DAEMON   Heres why your blood sugar is so erratic Consistent diet but...

 4 valid new messages out of 5 new messages and 106 total messages
 Ignoring 21 messages with an evil 'From ' field out of 106 total messages
 Ignoring 1 messages with an evil 'From ' field out of 5 new messages
.SH DESCRIPTION
.I spam-summary
checks one or more mailboxes that are suspected spam and
creates a report showing the sender and subject, one message per line,
of new messages that have arrived in that mailbox since the last time run.
.PP
A typical usage is that the user has mail forwarded, via a .forward file,
into procmail that has a number of rules to capture suspect spam mail,
and writes it to one or more spam mailboxes.  Typically, procmail is
making use of \fIspamassassin\fP.   Then \fIspam-summary\fP is typically run each
night from the crontab that looks at those mailboxes and produces a short
simple report showing address and subject - which is then mailed to you.
.PP
This way you can quickly verify that there are no false positives of real
mail that ended up as spam.  Since there should be a small number of new
spam messages each day, it is more manageable than wading through hundreds or
thousands over some irregular time interval by ocassionally checking manually.
.PP
It is driven by a config file to specify where the spam mailboxes are, and
where the timestamps are located.
.SH REQUIREMENTS
.I spam-summary
uses the Moxad::Config module to handle human-readable config files. This
is available at https://github.com/rjwhite/Perl-config-module
.SH CONFIG FILE
The config file is expected to be found in ${HOME}/etc/spam-summary/spam-summary.conf
.PP
It can contain a section called \fBvariables\fP where you can set some scalar variables
that can expanded in other sections by surrounding them like a shell variable, such 
as ${\fBvariable\fP}.
.PP
The name of a spam mailbox begins in column one.  If it has spaces in it, then you will 
need to quote the name if specifically specifying that mailbox to \fIspam-summary\fP, such as:
.br
.ti +3
\fIspam-summary "Probably Spam"\fP
.PP
There are 6 indented keywords that can be set in a mailbox definition section:
 \fBtitle\fP                 the title printed in the report
 \fBfolder\fP                the filename of the mailbox
 \fBtimestamp-file\fP        the filename of the timestamp of last run
 \fBignore-from-patterns\fP  a filename of patterns to watch for and reject
 \fBaddress-max-len\fP       the maximum length of the address.  Chop if necessary
 \fBfind-hidden-sender\fP    optional, defaults to \fBno\fP.  
.PP
If the \fBfind-hidden-sender\fP keyword is set to \fByes\fP for this mailbox,
then \fIspam-summary\fP will try harder to find the \fBFrom\fP address since
this is probably a mailbox of bounced mail messages that come from MAILER-DAEMON.
It will look into the body of the message as well as the header to find one.
.PP
You can specify patterns in the e-mail address for messages to ignore from ongoing spammers
that have consistent forged addresses by using the \fBignore-from-patterns\fP
keyword specifying a file of patterns to match.  If a match is found in an
address, then it is considered an Evil address and skipped because we know it
is spam.  Comments in the file beginning with '#' and newlines will be ignored.
.SH Config file example
.nf
# variables to expand in entries
variables:
    main-dir        = /home/rj/etc/spam-summary
    timestamp-dir   = /home/rj/etc/spam-summary/time-stamps
    folder-dir      = /home/rj/Mutt-mail
    address-len-max = 22

Likely Spam:
    title                   = Almost Certainly Spam
    folder                  = ${folder-dir}/spam/almost-certainly-spam
    timestamp-file          = ${timestamp-dir}/likely.txt
    ignore-from-patterns    = ${main-dir}/from-patterns.txt
    address-max-len         = ${address-len-max}

Probably Spam:
    title                   = Probably Spam
    folder                  = ${folder-dir}/spam/probably-spam
    timestamp-file          = ${timestamp-dir}/probably.txt
    ignore-from-patterns    = ${main-dir}/from-patterns.txt
    address-max-len         = ${address-len-max}

Best TLD:
    title                   = Crap from the Best Top Level Domain
    folder                  = ${folder-dir}/spam/best-top-level-domain
    timestamp-file          = ${timestamp-dir}/best-TLD.txt
    ignore-from-patterns    = ${main-dir}/from-patterns.txt
    address-max-len         = ${address-len-max}

mailer-daemon:
    title                   = Bounced Mail
    folder                  = ${folder-dir}/mailer-daemon
    timestamp-file          = ${timestamp-dir}/mailer-daemon.txt
    ignore-from-patterns    = ${main-dir}/from-patterns.txt
    address-max-len         = ${address-len-max}
    find-hidden-sender      = yes
.fi
.SH TIMESTAMP FILES
\fIspam-summary\fP only shows messages since the last time it was run - unless you 
specify the -i or --ignore option to ignore the timestamp of the last run for
a particular folder.  The location of these timestamp files is specified in
the config file.  A typical timestamp file is given below.  The comments,
beginning with '#' are part of the file and are ignored by the program when 
reading it to get the numeric timestamp.
.TP 0
  # This timestamp file written by the spam-summary program
  # This timestamp is for the 'Probably Spam' mail folder
  # The timestamp below is Thu Oct 27 06:34:40 2022
    
  1666852480
.SH MAINTENANCE 
\fIspam-summary\fP does not do any cleanup of the spam mail folders.  It is up to
you to ocassionally remove them or remove really old messages from it.
Unless you have awful disk constraints and enormous amounts of spam mail,
you can probably clean them up every year or two.  Generally, you'd probably
do it when you see the \fBtotal messages\fP at the end of your regular (daily?)
report become some large number - like many thousands.
.SH AUTHOR
RJ White
.br
rj.white@moxad.com
.br
Moxad Enterprises Inc.
